// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/processor.proto

package processor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FFmpegProcessor_ProcessStream_FullMethodName = "/processor.FFmpegProcessor/ProcessStream"
)

// FFmpegProcessorClient is the client API for FFmpegProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FFmpegProcessorClient interface {
	// Bidirectional streaming — client sends input chunks + args,
	// server streams processed output chunks back.
	ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessRequest, ProcessResponse], error)
}

type fFmpegProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewFFmpegProcessorClient(cc grpc.ClientConnInterface) FFmpegProcessorClient {
	return &fFmpegProcessorClient{cc}
}

func (c *fFmpegProcessorClient) ProcessStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessRequest, ProcessResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FFmpegProcessor_ServiceDesc.Streams[0], FFmpegProcessor_ProcessStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessRequest, ProcessResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegProcessor_ProcessStreamClient = grpc.BidiStreamingClient[ProcessRequest, ProcessResponse]

// FFmpegProcessorServer is the server API for FFmpegProcessor service.
// All implementations must embed UnimplementedFFmpegProcessorServer
// for forward compatibility.
type FFmpegProcessorServer interface {
	// Bidirectional streaming — client sends input chunks + args,
	// server streams processed output chunks back.
	ProcessStream(grpc.BidiStreamingServer[ProcessRequest, ProcessResponse]) error
	mustEmbedUnimplementedFFmpegProcessorServer()
}

// UnimplementedFFmpegProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFFmpegProcessorServer struct{}

func (UnimplementedFFmpegProcessorServer) ProcessStream(grpc.BidiStreamingServer[ProcessRequest, ProcessResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessStream not implemented")
}
func (UnimplementedFFmpegProcessorServer) mustEmbedUnimplementedFFmpegProcessorServer() {}
func (UnimplementedFFmpegProcessorServer) testEmbeddedByValue()                         {}

// UnsafeFFmpegProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FFmpegProcessorServer will
// result in compilation errors.
type UnsafeFFmpegProcessorServer interface {
	mustEmbedUnimplementedFFmpegProcessorServer()
}

func RegisterFFmpegProcessorServer(s grpc.ServiceRegistrar, srv FFmpegProcessorServer) {
	// If the following call pancis, it indicates UnimplementedFFmpegProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FFmpegProcessor_ServiceDesc, srv)
}

func _FFmpegProcessor_ProcessStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FFmpegProcessorServer).ProcessStream(&grpc.GenericServerStream[ProcessRequest, ProcessResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegProcessor_ProcessStreamServer = grpc.BidiStreamingServer[ProcessRequest, ProcessResponse]

// FFmpegProcessor_ServiceDesc is the grpc.ServiceDesc for FFmpegProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FFmpegProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processor.FFmpegProcessor",
	HandlerType: (*FFmpegProcessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessStream",
			Handler:       _FFmpegProcessor_ProcessStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/processor.proto",
}
